services:
  top3_db:
    image: postgres:14.1-alpine
    container_name: "top3_db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

  top3_bot:
    container_name: "top3_bot"
    depends_on:
      - db_top3
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 bot.py
    volumes:
      - .:/bot
    environment:
      - RUN_WITH_DOCKER=True
    env_file:
      - .env
    restart: always