services:
  db:
    image: postgres:14.1-alpine
    container_name: "db"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
